/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/defaced/detail" |
       "/pages/defaced/list" |
       "/pages/mine/mine" |
       "/pages/mine/settings" |
       "/pages/notice/index" |
       "/pages/notice/site" |
       "/pages/order/detail" |
       "/pages/order/list" |
       "/pages/product/detail" |
       "/pages/product/pay" |
       "/pages/single/about" |
       "/pages/single/rich" |
       "/pages/single/system" |
       "/pages/site/site" |
       "/pages-site/order/acceptance" |
       "/pages-site/order/defaced" |
       "/pages-site/order/defacedDetail" |
       "/pages-site/order/detail" |
       "/pages-site/order/issue" |
       "/pages-site/order/refund";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/site/site" | "/pages/mine/mine"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
