/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BfCalendar: typeof import('./../components/bf-calendar/bf-calendar.vue')['default']
    BfDatePicker: typeof import('./../components/bf-date-picker/bf-date-picker.vue')['default']
    BfEmpty: typeof import('./../components/bf-empty/bf-empty.vue')['default']
    BfModuleHead: typeof import('./../components/bf-module-head/bf-module-head.vue')['default']
    BfProduct: typeof import('./../components/bf-product/bf-product.vue')['default']
    BfSite: typeof import('./../components/bf-site/bf-site.vue')['default']
    BfSitePopup: typeof import('./../components/bf-site-popup/bf-site-popup.vue')['default']
    BfSkuPopup: typeof import('./../components/bf-sku-popup/bf-sku-popup.vue')['default']
    BfSwiper: typeof import('./../components/bf-swiper/bf-swiper.vue')['default']
    Component: typeof import('./../components/component/component.vue')['default']
    LoadImage: typeof import('./../components/load-image/load-image.vue')['default']
    NutAnimate: typeof import('nutui-uniapp/components/animate/animate.vue')['default']
    NutAvatar: typeof import('nutui-uniapp/components/avatar/avatar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCalendar: typeof import('nutui-uniapp/components/calendar/calendar.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutCheckbox: typeof import('nutui-uniapp/components/checkbox/checkbox.vue')['default']
    NutCollapse: typeof import('nutui-uniapp/components/collapse/collapse.vue')['default']
    NutCollapseItem: typeof import('nutui-uniapp/components/collapseitem/collapseitem.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutCountdown: typeof import('nutui-uniapp/components/countdown/countdown.vue')['default']
    NutDatePicker: typeof import('nutui-uniapp/components/datepicker/datepicker.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutPicker: typeof import('nutui-uniapp/components/picker/picker.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutRadio: typeof import('nutui-uniapp/components/radio/radio.vue')['default']
    NutRadioGroup: typeof import('nutui-uniapp/components/radiogroup/radiogroup.vue')['default']
    NutSwitch: typeof import('nutui-uniapp/components/switch/switch.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
    NutTag: typeof import('nutui-uniapp/components/tag/tag.vue')['default']
  }
}
